[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "forge-std/=lib/forge-std/src/",

    "@uniswap/v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "@uniswap/hooks/=lib/uniswap-hooks/src/",

    "hookmate/=lib/hookmate/src/",
    "solmate/=lib/uniswap-hooks/lib/v4-core/lib/solmate/",

    "@aave/=lib/protocol-v3/contracts/",
    "@pythnetwork/=node_modules/@pythnetwork/pyth-sdk-solidity",
    "@permit2/=lib/permit2/",
    "@openzeppelin/=lib/openzeppelin-contracts/",

    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/",
    "@uniswap/universal-router/=lib/universal-router/"
]
